# Generated by Django 3.2.3 on 2023-08-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_auto_20230814_0149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="tagrecipe",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.tag"
            ),
        ),
    ]
